spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.107:3306/mppr_linkage?useSSL=false
    username: root
    password: 123456

  rabbitmq:
    port: 5672
    host: 192.168.8.107
    username: admin
    password: 123456 

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html

server:
  port: 9102
  
feign:
  hystrix:
    enabled: true
  
turbine:
  appConfig: mppr-message-service
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")

sms:
 uid: username
 key: key
 url: http://gbk.api.smschinese.cn
 
 context:
   listener:
     classes: com.gato.yun.mppr.linkage.service.listener.WebSocketListener

mybatis:
  typeAliasesPackage: com.gato.yun.mppr.linkage.service.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cacheEnabled: true
    useGeneratedKeys: true
    defaultExecutorType: reuse
    mapUnderscoreToCamelCase: true

management:
  security:
    enabled: false

eureka.client.healthcheck.enabled: false

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


