spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.107:3306/mppr_vehicle
    username: root
    password: 123456

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html

server:
  port: 9230

mybatis:
  typeAliasesPackage: com.gato.yun.mppr.vehicle.service.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cacheEnabled: true
    useGeneratedKeys: true
    defaultExecutorType: reuse
    mapUnderscoreToCamelCase: true

management:
  security:
    enabled: false

eureka.client.healthcheck.enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
