spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cdb-ljjztg90.sql.tencentcdb.com:63054/gato_db
    username: root
    password: caoyang821821821
  rabbitmq:
    port: 5672
    host: 192.168.9.170
    username: admin
    password: 123456


eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html

server:
  port: 9101
  
feign:
  hystrix:
    enabled: true
  
turbine:
  appConfig: mppr-message-service
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")

sms:
 uid: username
 key: key
 url: http://gbk.api.smschinese.cn
 
mail:
  host: smtp.qq.com
  port: 587
  username: 1621023101@qq.com
  password: bjtlstxsgatndaad
  

mybatis:
  typeAliasesPackage: com.gato.yun.message.service.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cacheEnabled: true
    useGeneratedKeys: true
    defaultExecutorType: reuse
    mapUnderscoreToCamelCase: true

management:
  security:
    enabled: false

eureka.client.healthcheck.enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
