spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.9.170:3306/mppr_linkage?useSSL=false
    username: root
    password: 123456
  rabbitmq:
    port: 5672
    host: 192.168.9.170
    username: admin
    password: 123456

server:
  port: 9101
  
  
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  
  
turbine:
  appConfig: mppr-message-service
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")

sms:
 uid: username
 key: key
 url: http://gbk.api.smschinese.cn
 
mail:
  host: smtp.qq.com
  port: 587
  username: 1621023101@qq.com
  password: bjtlstxsgatndaad
  

mybatis:
  typeAliasesPackage: com.gato.yun.message.service.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cacheEnabled: true
    useGeneratedKeys: true
    defaultExecutorType: reuse
    mapUnderscoreToCamelCase: true

management:
  security:
    enabled: false

eureka.client.healthcheck.enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
