spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cdb-ljjztg90.sql.tencentcdb.com:63054/gato_db
    username: root
    password: caoyang821821821
   
  rabbitmq:
    port: 5672
    host: 140.143.96.122
    username: admin
    password: 123456 
  
  redis:
        host: 192.168.8.107
        port: 6379
        password:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000  


server:
  port: 9000

management:
  security:
    enabled: false

mybatis:
  typeAliasesPackage: com.gato.yun.mppr.face.service.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cacheEnabled: true
    useGeneratedKeys: true
    defaultExecutorType: reuse
    mapUnderscoreToCamelCase: true


key:
  99999

eureka.client.healthcheck.enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
