spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.9.170:3306/mppr_face?useSSL=false
    username: root
    password: 123456
   
  rabbitmq:
    port: 5672
    host: 192.168.9.170
    username: admin
    password: 123456 
  
  redis:
        host: 192.168.9.170
        port: 6379
        password:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000  


server:
  port: 9888

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000


eureka.client.healthcheck.enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
