spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.9.170:3306/mppr_face?useSSL=false
    username: root
    password: 123456
  
  
  rabbitmq:
    port: 5672
    host: 192.168.9.170
    username: admin
    password: 123456 
  
  redis:
        host: 192.168.9.170
        port: 6379
        password:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000  

zuul:
  #忽略所有敏感头
  sensitive-headers:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    account:
      path: /jcfgs/**
      serviceId: mppr-jcfgs-service
      sensitiveHeaders:
    mppr-vehicle-service:
      path: /mppr-vehicle/**
      serviceId: mppr-vehicle-service
    mppr-access-service:
      path: /mppr-access/**
      serviceId: mppr-access-service
    mppr-linkage-service:
      path: /mppr-linkage/**
      serviceId: mppr-linkage-service
    mppr-message-service:
      path: /mppr-message/**
      serviceId: mppr-message-service
    mppr-face-service:
      path: /mppr-face/**
      serviceId: mppr-face-service


server:
  port: 5000

management:
  security:
    enabled: false
