spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.9.170:3306/jcfgs?useSSL=false
    username: root
    password: 123456
    initialSize: 1
    maxActive: 5
    minIdle: 1
    maxWait: 60000
    filters: stat,log4j,wall
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
   
  rabbitmq:
    port: 5672
    host: 192.168.9.170
    username: admin
    password: 123456 
  
  redis:
        host: 192.168.9.170
        port: 6379
        password:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000  


server:
  port: 9300

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka.client.healthcheck.enabled: false    
    

mybatis:
  typeAliasesPackage: com.gato.yun.mppr.jcfgs.service.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cacheEnabled: true
    useGeneratedKeys: true
    defaultExecutorType: reuse
    mapUnderscoreToCamelCase: true
#日志配置
logback:
  logdir: /datalog/jcfgs
  appname: cfgs-log
logging:
  config: classpath:logback-spring-local.xml
  
#feign:
#  httpclient:
#    enabled: true  
#远程调用c++
remoteUrl: http://192.168.8.67:9300 


