spring:
  datasource:
      name: test
      url: jdbc:mysql://192.168.9.170:3306/mppr_vids?&useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      logSlowSql: true
  rstp:
    host: 192.168.9.137
    port: 20001
  rabbitmq:
    virtual-host: /
    password: 123456
    host: 5672
    username: admin
    addresses: 192.168.9.170
server:
  port: 8089

mybatis:
    basepackage: com.gato.yun.mppr.vids.service.dao
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"